name = "marketai"
type = "javascript"
account_id = ""
workers_dev = true
main = "src/index.js"

[env.production]
name = "marketai-prod"
route = "api/*"

[[kv_namespaces]]
binding = "DATA"
id = "market-data"
preview_id = "market-data-preview"

[build]
command = ""
cwd = "./"

[build.upload]
format = "service-worker"
main = "./src/index.js"

[triggers.crons]
crons = ["*/5 8-15 * * 1-5"]
